name: Scrape V2Ray Configs

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '20 * * * *'

jobs:
  build-and-commit:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r locsort/requirements.txt

      - name: Run the main script
        run: python locsort/main.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A .
          git diff-index --quiet HEAD || git commit -m "Automated config refresh completed at: $(TZ='Asia/Tehran' date '+%H:%M:%S')"
          git pull --rebase origin main
          git push
